Update

diff --git a/.github/workflows/blank1.yml b/.github/workflows/blank1.yml
--- a/.github/workflows/blank1.yml
+++ b/.github/workflows/blank1.yml
@@ -19,12 +19,12 @@ jobs:
           node-version: 22.3.0
           
       - name: Install newman
-        run: sudo npm i newman  # Specify the desired version of newman
+        run: sudo npm i newman@latest
          
       - name: Run Postman collections and generate JUnit XML reports
         run: |
-          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" --disable-unicode --insecure
-          newman run "Collection2.json" -r junit --reporter-junit-export "SampleArtifact/report2.xml" --disable-unicode --insecure
+          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" --disable-unicode --insecure --verbose || echo "Collection1 failed" >> SampleArtifact/error.log
+          newman run "Collection2.json" -r junit --reporter-junit-export "SampleArtifact/report2.xml" --disable-unicode --insecure --verbose || echo "Collection2 failed" >> SampleArtifact/error.log
       
       - name: Set up Python
         uses: actions/setup-python@v4
@@ -58,3 +58,10 @@ jobs:
         with:
           name: Comparison Output
           path: SampleArtifact/comparison_output.txt
+
+      - name: Publish Error Log
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Error Log
+          path: SampleArtifact/error.log
