Update

diff --git a/.github/workflows/Workflow2.yml b/.github/workflows/Workflow2.yml
--- a/.github/workflows/Workflow2.yml
+++ b/.github/workflows/Workflow2.yml
@@ -1,45 +1,21 @@
-name: Workflow 2
+name: Workflow 1
 
 on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-  workflow_dispatch:
+    push:
+      branches: [ "main" ]
+    pull_request:
+      branches: [ "main" ]
+    workflow_dispatch:
 
 jobs:
   build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout the current commit
-        uses: actions/checkout@v4
-
+      - uses: actions/checkout@v4
+      
       - name: Creating directory for artifacts
         run: mkdir -p SampleArtifact
-
-      - name: Check if previous commit exists
-        id: previous_commit_check
-        run: |
-          if [ $(git rev-list --count HEAD) -gt 1 ]; then
-            echo "previous_commit_exists=true" >> $GITHUB_ENV
-          else
-            echo "previous_commit_exists=false" >> $GITHUB_ENV
-          fi
-
-      - name: Checkout the previous commit
-        if: env.previous_commit_exists == 'true'
-        run: |
-          git fetch --all
-          git checkout HEAD~1
-
-      - name: Copy previous Collection1.json to artifacts
-        if: env.previous_commit_exists == 'true'
-        run: cp Collection1.json SampleArtifact/Collection1_previous.json
-
-      - name: Checkout back to the current commit
-        if: env.previous_commit_exists == 'true'
-        run: git checkout -
 
       - name: Setting up Node.js
         uses: actions/setup-node@v4
@@ -48,39 +24,52 @@ jobs:
           
       - name: Installing Newman
         run: sudo npm i newman@latest
-         
-      - name: Running current Postman collection and generating JUnit XML report
-        run: |
-          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report_current.xml" || echo "Collection1 failed" >> SampleArtifact/error_current.log
+      
+      - name: Checking if previous commit exists
+        id: prev_commit
+        run: echo "::set-output name=exists::$(git rev-parse HEAD~1 || echo 'no')"
 
-      - name: Running previous Postman collection and generating JUnit XML report
-        if: env.previous_commit_exists == 'true'
+      - name: Fetching previous commit
+        if: steps.prev_commit.outputs.exists != 'no'
+        run: git fetch --depth=2 && git checkout HEAD~1
+
+      - name: Copying previous report
+        if: steps.prev_commit.outputs.exists != 'no'
         run: |
-          newman run "SampleArtifact/Collection1_previous.json" -r junit --reporter-junit-export "SampleArtifact/report_previous.xml" || echo "Collection1_previous failed" >> SampleArtifact/error_previous.log
+          mkdir -p SampleArtifact/previous
+          cp -v "SampleArtifact/report1.xml" "SampleArtifact/previous/report1.xml"
+      
+      - name: Checkout current commit
+        if: steps.prev_commit.outputs.exists != 'no'
+        run: git checkout -
+
+      - name: Running Postman collection and generating JUnit XML report
+        run: |
+          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log
       
       - name: Setting up Python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.x'
+            python-version: '3.x'
 
-      - name: Running the Python script to compare XML reports
-        if: env.previous_commit_exists == 'true'
+      - name: Running the Python script for comparison
+        if: steps.prev_commit.outputs.exists != 'no'
         run: |
           python compare_xml.py > SampleArtifact/comparison_output.txt
         env:
-          XML_FILE1: SampleArtifact/report_previous.xml
-          XML_FILE2: SampleArtifact/report_current.xml
+          XML_FILE1: SampleArtifact/previous/report1.xml
+          XML_FILE2: SampleArtifact/report1.xml
 
       - name: Publishing JUnit XML Reports
         uses: actions/upload-artifact@v4
         with:
           name: JUnit Reports
           path: |
-            SampleArtifact/report_current.xml
-            SampleArtifact/report_previous.xml
+            SampleArtifact/report1.xml
+            SampleArtifact/previous/report1.xml
 
       - name: Publishing the comparison output
-        if: env.previous_commit_exists == 'true'
+        if: steps.prev_commit.outputs.exists != 'no'
         uses: actions/upload-artifact@v4
         with:
           name: Comparison Output
