Update

diff --git a/.github/workflows/Workflow2.yml b/.github/workflows/Workflow2.yml
--- a/.github/workflows/Workflow2.yml
+++ b/.github/workflows/Workflow2.yml
@@ -1,4 +1,4 @@
-name: Workflow 1
+name: Workflow 2
 
 on:
     push:
@@ -6,7 +6,7 @@ on:
     pull_request:
       branches: [ "main" ]
     workflow_dispatch:
-  
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -25,23 +25,19 @@ jobs:
       - name: Installing Newman
         run: sudo npm i newman@latest
          
-      - name: Determine report number
-        id: report_number
-        run: echo "::set-output name=report_number::$(($(git rev-list --count HEAD) + 1))"
-
-      - name: Running Postman Collection and generating JUnit XML report
+      - name: Running Postman Collection 1 and generating JUnit XML report
         run: |
-          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report${{ steps.report_number.outputs.report_number }}.xml" || echo "Collection1 failed" >> SampleArtifact/error${{ steps.report_number.outputs.report_number }}.log
+          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log
 
       - name: Publishing JUnit XML Report
         uses: actions/upload-artifact@v4
         with:
           name: JUnit Report for Collection1
-          path: SampleArtifact/report${{ steps.report_number.outputs.report_number }}.xml
+          path: SampleArtifact/report1.xml
 
       - name: Publishing error log (if any)
         if: failure()
         uses: actions/upload-artifact@v4
         with:
           name: Error Log for Collection1
-          path: SampleArtifact/error${{ steps.report_number.outputs.report_number }}.log
+          path: SampleArtifact/error1.log
