Update

diff --git a/.github/workflows/Workflow2.yml b/.github/workflows/Workflow2.yml
--- a/.github/workflows/Workflow2.yml
+++ b/.github/workflows/Workflow2.yml
@@ -25,20 +25,19 @@ jobs:
       - name: Installing Newman
         run: sudo npm i newman@latest
          
-      - name: Running Postman collections and generating JUnit XML reports
+      - name: Running Postman Collection 1 and generating JUnit XML report
         run: |
-          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report1.xml" || echo "Collection1 failed" >> SampleArtifact/error1.log
+          newman run "Collection1.json" -r junit --reporter-junit-export "SampleArtifact/report-${{ github.sha }}.xml" || echo "Collection1 failed" >> SampleArtifact/error-${{ github.sha }}.log
 
-      - name: Publishing JUnit XML Reports
+      - name: Publishing JUnit XML Report
         uses: actions/upload-artifact@v4
         with:
-          name: JUnit Reports
-          path: |
-            SampleArtifact/report1.xml
+          name: JUnit Report for Commit ${{ github.sha }}
+          path: SampleArtifact/report-${{ github.sha }}.xml
 
-      - name: Publishing error logs (if any)
+      - name: Publishing error log (if any)
         if: failure()
         uses: actions/upload-artifact@v4
         with:
-            name: Error Logs
-            path: SampleArtifact/error*.log
+          name: Error Log for Commit ${{ github.sha }}
+          path: SampleArtifact/error-${{ github.sha }}.log
