Update

diff --git a/.github/workflows/Workflow4.yml b/.github/workflows/Workflow4.yml
--- a/.github/workflows/Workflow4.yml
+++ b/.github/workflows/Workflow4.yml
@@ -1,41 +1,37 @@
-name: Compare XML Reports
+name: Workflow 4
 
 on:
-  push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
   workflow_dispatch:
 
 jobs:
-  compare_reports:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
+      - uses: actions/checkout@v4
+      
+      - name: Setting up Node.js
+        uses: actions/setup-node@v4
         with:
-          python-version: '3.x'
-
-      - name: Compare XML reports
+          node-version: '22.3.0'
+          
+      - name: Installing Newman
+        run: npm install -g newman@latest
+         
+      - name: Running Postman Collection 1 and generating JUnit XML report
         run: |
-          # Fetch the commits of interest and their corresponding report files
-          git fetch origin
-          git checkout ${{ github.event.before }}
-          cp SampleArtifact/report1.xml report1.xml
-          git checkout ${{ github.sha }}
-          cp SampleArtifact/report1.xml report2.xml
+          mkdir -p reports
+          newman run "Collection1.json" -r junit --reporter-junit-export "reports/report1.xml" || echo "Collection1 failed" >> reports/error1.log
 
-          # Run comparison script
-          python compare_xml.py report1.xml report2.xml > SampleArtifact/comparison_output.txt
-
-      - name: Upload comparison output
-        uses: actions/upload-artifact@v2
+      - name: Publishing JUnit XML Report
+        uses: actions/upload-artifact@v4
         with:
-          name: Comparison Output
-          path: SampleArtifact/comparison_output.txt
+          name: JUnit Report for Collection1
+          path: reports/report1.xml
+
+      - name: Publishing error log (if any)
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: Error Log for Collection1
+          path: reports/error1.log
